from django.core.exceptions import ValidationError


def validate_pesel(pesel):
    pass
